### ISSUE TITLE
Unknown line format error for multiline log while incremental analysis over ssh

### ISSUE THREAD

**Issue by wycho** [darold/pgbadger#449]
pgBadger version 10.1

I ran the following command several times. From second time it prints "DEBUG: Unknown line format:   ...." errors for multiline queries.
`pgbadger -v -I -O /home/user/pg_reports -r remote_host /var/log/postgresql/postgresql-10-main.log`

If I run pgbadger on the remote host using same log file, it seems ok.

I don't use custom prefix. The following is a sample problematic log.
```
2018-10-19 09:00:55.089 KST [5027] jsa@jsa LOG:  duration: 38.632 ms  statement: select
                    json_build_object(
                    'USERS', MAX(case when t.VARIABLE_NAME = 'USERS' THEN t.VARIABLE_VALUE ELSE NULL END),
...

```

**Comment by darold** [comment]
Hi,

You are using a custom prefix, add the following to your pgbadger command line that should work:
```
--prefix '%m [%p] %u@%d '
```
Adjust to what is defined in your `log_line_prefix` postgresql.conf configuration directive if this is not exactly the above value.

**Comment by wcho** [comment]
Thank you.
I thought I'm not using custom prefix because I didn't set it manually.
I got system default `log_line_prefix` value `"%m [%p] %q%u@%d "` using `SHOW log_line_prefix;`.
But the problem still occurs even with `--prefix '%m [%p] %q%u@%d '` option. I also cleaned `pg_reports/*` and ran `pgbadger` again several times. It still shows error messages for multiline query logs from second run.

**Comment by darold** [comment]
Please send your log to my private email address < gilles AT darold DOT net >.
