### ISSUE TITLE
Improve multiprocess

### ISSUE THREAD

**Issue by darold** [darold/pgbadger#463]
Reported by @raptelan: As a possible future enhancement, would it be possible to split the file into a lot more chunks, work on 16 at a time, and whichever one finishes first grabs another small chunk out of the remaining pool? I was hoping to keep the CPU's all busy, as I am processing logs from dozens of hosts, some of which have pretty large logs.

**Comment by wsdookadr** [comment]
If this issue is still open I'm assuming it's still on the table for consideration.
I was reading through this, and I'm trying to understand the reasoning behind it. I think it's different than `-j X` which processes multiple log files in parallel. So in this issue we're wanting to parallelize the processing of a single file (as I understand it), let's suppose the new switch will be called `-k X`.

I think this entails the following points: 
1. how fast pgbadger is able to process data as compared to disk throughput ?
2. can splitting be done faster than doing a first-pass to determine offsets of all line-endings? 

If the answer to [1] is something like 10 MB/s and the disk throughput of that specific disk is 200 MB/s I suppose parallelization would help to get a 10x speedup at best but at the cost of exhausting all the disk I/O on that machine, but that may be fine since if a user would want to do this they would know beforehand to maybe copy logs to a place that's intended just for log analysis (?). At the same time they could use lower values of `-k X` to make sure they don't exhaust all the disk throughput.

About [2] , even assuming line ending offsets are known, something I don't know is how to determine the chunk boundary properly because there could multiline log lines, and I guess here the question is how pgbadger does it currently or if given a certain line number it can go back a few lines to determine the best boundary for the chunk.

I was also thinking that the alternative to having this new `-k X` switch would be for the user to adjust their `log_rotation_size` or `log_rotation_age` parameters in `postgresql.conf` and by doing so, smaller log files will be produced, and rotated more often and then `-j X` can be used instead on the resulting smaller files.

Other than that, pgbadger already has logic in-place for incremental log processing so aggregating statistics from chunk-level to file-level would be similar.
