### ISSUE TITLE
Queries from ERROR message not truncated by --maxlength switch

### ISSUE THREAD

**Issue by madtibo** [darold/pgbadger#470]
I had a crash in Firefox when opening a report with an error with a statement of some hundreds of MB.

The use of the maxlength switch did not solve the issue. Since this switch truncates queries and not statements.

**Comment by darold** [comment]
I think this part should be completely rewritten. The problem is that the truncation is done before normalization and reporting a truncated query is quite useless too. I think we should better:

- normalize the query and reserved parameters
- detect parameters with huge size and truncate them.
- recreate the query with  parameters truncated if any.

In this case perhaps we can consider that a parameter value upper than 1KB can be truncated.

**Comment by darold** [comment]
Commit 5e88446 change the behavior of pgbadger with very long queries.
```
   When a query is > 10Kb we first limit size of all constant string
    parameters to 30 characters and then the query is truncated to 10Kb.
    This prevent pgbadger to waste time/hang with very long queries
    when inserting bytea for example. The 10Kb limit can be controlled
    with the --maxlength command line parameter.
```
The query is normalized or truncated to `--maxlength` value only after this first attempt to limit size.
