### ISSUE TITLE
Incremental mode does not work with binary input

### ISSUE THREAD

**Issue by tbe** [darold/pgbadger#507]
If binary input is used for pgbadger, only a `index.html` is generated, but no report.

Running in debug mode shows:

```
[========================>] Parsed 1711399 bytes of 1711399 (100.00%), queries: 131059, events: 100
DEBUG: the log statistics gathering took: 6 wallclock secs ( 0.07 usr  0.02 sys +  0.09 cusr  0.03 csys =  0.21 CPU)
DEBUG: no new entries in your log(s) since last run.
LOG: Ok, generating global index to access incremental reports...
```

**Comment by darold** [comment]
What pgbadger commands are you using?

**Comment by tbe** [comment]
Testet with 10.2 and 10.3

**Comment by darold** [comment]
I was asking for the pgbadger command line, not the version :-)

**Comment by tbe** [comment]
I will provide them monday, as i'm back in office

**Comment by tbe** [comment]
Here are the commands:

Generating the binary files with
```
pgbadger -q - -o something-1.bin -f stderr
pgbadger -q - -o something-2.bin -f stderr
pgbadger -q - -o something-3.bin -f stderr
...
```

Finald build:
```
pgbadger -I -O '/some/report/dir' something-1.bin something-2.bin something-3.bin ...
```
We have a centralized logging instance with a timescale backend. We run several copy jobs in parallel to our wrapper. The files a generated in chronological order.

**Comment by darold** [comment]
This use is not supported, If you want to use incremental mode it must be used to generate the binary files too. With your binary files you can just generate e single HTML report as follow:
```
pgbadger -o '/some/report/dir/index.html' something-1.bin something-2.bin something-3.bin ...
```

To use the incremental mode you just have to run pgbadger using a single command when you are processing your log files:
```
pgbadger -I -O '/some/report/dir' -q -f stderr -
```
pgBadger will write binary files under '/some/report/dir' in a time based tree that is necessary for building incremental reports. The problem is that you must process the log entries from the older to the newer date otherwise some entries can be skipped due to the fact that the current parsing date is newer that the log entry sent. If you can't send the log entries ordered by timestamp you can build your own incremental tree by date, for example:
```
mkdir -p /some/report/dir/2019/06/12/
pgbadger -q - -o /some/report/dir/2019/06/12/something-1.bin -f stderr
mkdir -p /some/report/dir/2019/06/13/
pgbadger -q - -o /some/report/dir/2019/06/13/something-1.bin -f stderr
```
then build the reports:
```
pgbadger -o /some/report/dir/2019/06/12/index.html /some/report/dir/2019/06/12/something-1.bin
pgbadger -o /some/report/dir/2019/06/13/index.html /some/report/dir/2019/06/13/something-1.bin
```
and finally rebuild the global index:
```
pgbadger -I -O '/some/report/dir' --rebuild
```
You should also compute the week report by yourself. This is a huge work when you know that this is done automatically by pgbadger when you can pass the log entries ordered by timestamp.
