### ISSUE TITLE
Skipped logs when format is specified

### ISSUE THREAD

**Issue by birkosan** [darold/pgbadger#519]
Hi

I tried to process my logs with version 11.0, but it does not combine the pgbouncer and postgresql logs in the same report when log format is specified:

pgbadger --average 1 --sample 15 --top 50 --start-monday -I -J 4 -O $outputpath \
                pgbouncer.log -f stderr postgresql.log
With this command the pgbouncer section is missing. If I put the pgbouncer.log as last in the command, then the postgresql data is missing. It seems only the last logfile (or logfile type) is processed.

I tried to process only the pgbouncer first, checked the report, then process the postgresql log and the pgbouncer data was eliminated from the report, remain just the postgresql data.

When I doesn't specify the log format works well, but sometimes I have multiple logfiles in the same day (postgres service restarts, etc) and some logfile format wasn't auto-detected and I get errors and the process just stops.

This behavior does not apply to versions before.

Thanks
Levi

**Comment by darold** [comment]
Hi

This is because the `-f` force the use of the `stderr` format for all log to parse which don't fit with pgbouncer log entries. Format for pgbouncer log is unsurprisingly named `pgbouncer`.

Since version 11 you can set the format to use per file by suffixing the log filename by `:format`. For your command it will be:
```
pgbadger --average 1 --sample 15 --top 50 --start-monday -I -J 4 -O $outputpath \
                pgbouncer.log:pgbouncer postgresql.log:stderr
```
Of course if `-f stderr` is not provided pgbadger will auto-detect the log format but as you said sometime it could throw an error about unknown log format. This is the case when pgbadger can not count 10 lines with the same auto-detected format in the first 5000 lines. So with very small file this can happen. In this case use the per log file format syntax, this is the same for remote log file:
```
pgbadger ..... ssh:///var/log/postgresql/postgresql.log:syslog
```

Regards,

**Comment by birkosan** [comment]
OK, I see.

This works only with specific file and perhaps could be implemented in the future like postgres*.log:stderr or pgbouncer*.log:pgbouncer

Thanks!
Levi

**Comment by darold** [comment]
Commit f32ee6f fixes this issue. Now the format specified with the `-f | --format` value is applied only to log file where format can not be detected whatever is the file list.
