### ISSUE TITLE
Support/Document the prefix for rds postgres logs streamed from cloudwatch

### ISSUE THREAD

**Issue by peruuparkar** [darold/pgbadger#521]
Hello ,
I am able to run pgbadger successfully with rds postgres logs with '%t:%r:%u@%d:[%p]:' prefix.  I download postgres log using  aws console. Now same logs if I download from cloudwatch, have different prefix .

Here is sample without clodwatch , 
2019-08-09 18:00:00 UTC:10.50.72.222(33436):lmn@lmn_db:[26802]:LOG:  duration: 13.817 ms  statement: SELECT id,name from abc 

----
Now same line with cloudwatch , 

2019-08-09T18:00:00.000Z 2019-08-09 18:00:00 UTC:10.50.72.222(33436):lmn@lmn_db:[26802]:LOG:  duration: 13.817 ms  statement: SELECT id,name from abc

-------

With cloudwatch there is an additional timestamp, and I don't what prefix could be supported /needed here? Since this is the common case, documenting it would help for additional pgbadger adoption across the community.

**Comment by bhushanuparkar2** [comment]
Logs from cloudwatch are streamed logs and hence it might require special processing. PbBadger throws the "DEBUG: Unknown stderr line format:" error . 

----- here is sample sql query from log file 
2019-08-08T00:49:34.000Z 2019-08-08 00:49:34 UTC:10.40.77.242(56266):xyz@xyz_db:[20474]:LOG:  duration: 5.076 ms  statement: SELECT col1, col2
	FROM sample1 JOIN sample2 ON sample1.id = sample2.id
	WHERE sample1.col3 = 'xyzxyz-1234-xyzw-abcd-abcd1abcd2abcd'
        ORDER BY 1 DESC

-- Please note the sql is spanned over few lines because streaming .
And here is output from pgbadger,

`pgbadger --prefix  '%t:%r:%u@%d:[%p]:' -f stderr --verbose t2.log
DEBUG: timezone not specified, using 25200 seconds
DEBUG: Output 'html' reports will be written to out.html
DEBUG: Autodetected log format 'stderr' from t2.log
DEBUG: pgBadger will use log format stderr to parse t2.log.
DEBUG: Starting progressbar writer process
DEBUG: Processing log file: t2.log
DEBUG: Starting reading file t2.log...
DEBUG: Start parsing postgresql log at offset 0 of file t2.log to 299
DEBUG: Unknown stderr line format:   0 bFROM sample1 JOIN sample2 ON sample1.id = sample2.id
DEBUG: Unknown stderr line format: 	WHERE sample1.col3 = 'xyzxyz-1234-xyzw-abcd-abcd1abcd2abcd'
DEBUG: Unknown stderr line format:         ORDER BY 1 DESC
[========================>] Parsed 299 bytes of 299 (100.00%), queries: 1, events: 0
DEBUG: the log statistics gathering took: 2 wallclock secs ( 0.00 usr +  0.01 sys =  0.01 CPU)
DEBUG: Output 'html' reports will be written to out.html
LOG: Ok, generating html report...
DEBUG: building reports took:  0 wallclock secs ( 0.02 usr +  0.01 sys =  0.03 CPU)
DEBUG: the total execution time took:  2 wallclock secs ( 0.02 usr +  0.02 sys =  0.04 CPU)`





----

**Comment by darold** [comment]
Thanks for the report, this require a specific development to support cloudwatch logs.

**Comment by darold** [comment]
Commit f76dbf9 adds support to RDS and CloudWatch format, they should be auto detected and your don't have to set any prefix.

**Comment by bhushanuparkar2** [comment]
Thank you very much for adding support for this feature, much appreciated.
