### ISSUE TITLE
Parsing Issue

### ISSUE THREAD

**Issue by lewisbass1** [darold/pgbadger#528]
When parsing our logs we are not getting any query values.  I have attached a sample postgres log.

The postgresql.conf file contains the following
log_line_prefix = '%t  [%p]: [%1-1]  User:%u '

i am running the program with the following command line

pgbadger -p '%t %h [%p]: [%l-1] user=%u ' sample1.log

an abbreviated example of our logs are attached.
[sample1.log](https://github.com/darold/pgbadger/files/3687652/sample1.log)

**Comment by darold** [comment]
Well the problem is double: your log_line_prefix is wrong and the prefix given to pgbadger is also wrong.

Please set at minimal your log_line_prefix as follow:
```
log_line_prefix = '%t [%p]: User:%u '
```
but best would be to use the default pgBadger log_line_prefix. I don't want to force you, you may have your reasons to use this one but if you are not comfortable with pgbadger please use the default prefix with all information this will save us lot of time:
```
log_line_prefix = '%t [%p]: user=%u,db=%d,client=%h,app=%a '
```
Then use pgbadger without specifying any prefix.
