### ISSUE TITLE
Direct access to pev2

### ISSUE THREAD

**Issue by Krysztophe** [darold/pgbadger#571]
pgBadger can send a plan directly to explain.depesz.com. It would be fine to be able to send it to pev2  (démo : https://dalibo.github.io/pev2/#/  or https://explain.dalibo.com/ )

From a user point of view, I suppose that replacing  the link 'Explain plan' by 'Explain plan: on explain.depesz.com - on explain.dalibo.com' would be enough.

ping @pgiraud

**Comment by darold** [comment]
Actually I don't think think that pgBadger support explain plan in json format, so there might be some parsing adaptation. Otherwise yes we can allow this link to be change by a command line parameter.

**Comment by Krysztophe** [comment]
pev2 (not pev) accepts usual plans in pure text .

**Comment by darold** [comment]
ok I will give it a try.

**Comment by darold** [comment]
Commit 7c993f8 adds new option `--explain-url` to be able to redefine the URL for graphical explain.

**Comment by rjuju** [comment]
@darold it seems that this commit has some noise inside, eg.

- s/csv/cvs https://github.com/darold/pgbadger/commit/7c993f8bcd50c6c6870a8042814b4259b5e8bd0b#diff-04c6e90faac2675aa89e2176d2eec7d8R53
- s/2019/2919 https://github.com/darold/pgbadger/commit/7c993f8bcd50c6c6870a8042814b4259b5e8bd0b#diff-04c6e90faac2675aa89e2176d2eec7d8R313 https://github.com/darold/pgbadger/commit/7c993f8bcd50c6c6870a8042814b4259b5e8bd0b#diff-04c6e90faac2675aa89e2176d2eec7d8R679 and https://github.com/darold/pgbadger/commit/7c993f8bcd50c6c6870a8042814b4259b5e8bd0b#diff-04c6e90faac2675aa89e2176d2eec7d8R689

I also noted https://github.com/darold/pgbadger/commit/7c993f8bcd50c6c6870a8042814b4259b5e8bd0b#diff-04c6e90faac2675aa89e2176d2eec7d8R73.  As I understand the code, this should be a number of bytes rather than a number of character since files aren't open with an encoding specification.  I'm also wondering if as a consequence the `substr` call in store_queries() can truncate in the middle of a multibyte character?

**Comment by darold** [comment]
Good catch @rjuju looks like I have not updated the README.md file when committed  fd1f62d so this is done in this patch.

About the truncate size it is totally arbitrary, if I remember well this is the size of the bigger query I have seen in logs so I hope it will fit most of the situation to not truncate anything. But if it is truncated we don't care where it is truncated. Users that don't want their queries to be truncated will increase the `--maxlength` value to an other, high enough, arbitrary value :)
