### ISSUE TITLE
no data in "INSERT/UPDATE/DELETE Traffic" graph

### ISSUE THREAD

**Issue by alexandre-sk5** [darold/pgbadger#599]
Hello,

I have a problem with the "Insert/Update/Remove Traffic" graph. There is no data as you can see in the image below. 

Maybe the problem is in the rendering of the graph, as pgbadger seems to detect the queries (56 queries/sec peak).

I use CloudSQL. I generate reports with this command line : 
`pgbadger -f jsonlog -o pgbadger_report.html 05/*`

![image](https://user-images.githubusercontent.com/51441077/84004286-9be08980-a96b-11ea-8076-ede210cb2de3.png)

Thank you.

**Comment by darold** [comment]
Is it related to #590 ?

**Comment by alexandre-sk5** [comment]
Yes :) Now, it's working for all others graphs, except this particular graph.

**Comment by darold** [comment]
Commit cd05708 fixes the "General Activity" report where READ/WRITE queries count/duration was not reported.

About the "INSERT/UPDATE/DELETE Traffic" graph I think this is normal, this graph unlike the previous in this page, doesn't report the min/max/mean of the write queries but the average per 5 minutes. If they are all at 0 this is because the ratio `queries/300s` is near or equal to 0.
