### ISSUE TITLE
Some statements can be parsed while others not

### ISSUE THREAD

**Issue by czterocyty** [darold/pgbadger#653]
Hi,

pgBadger has some problems with parsing log files. Some logged statements are not parsed and analysed by pgBadger.

I prepared some branch on my repo to illustrate the problem:
https://github.com/czterocyty/pgbadger/blob/foo_bug/t/04_bug.t

See 04_bug.t file. There are two input files: two.log and three.log as test fixtures.

I expect both SELECT statements from log files are visible and parsed.

**Comment by wsdookadr** [comment]
## Code-related notes

[Ticket 347 (2017-05-24)](https://github.com/darold/pgbadger/issues/347)
was showing that pgbadger was partially able to parse prepared statements.

In that ticket we find that pgbadger was able to succesfully parse this query:

```
[DATE]:readonly@osm_rendering:[55055]:LOG:  duration: [number] ms  execute <unnamed>: SELECT ...

```

but not this query:

```
[DATE]:readonly@osm_rendering:[55031]:LOG:  duration: 26.151 ms  bind <unnamed>: SELECT ...
```

Later, in 2020-07-26 pgbadger added a new flag called --dump-all-queries which according to the brief description
in the help page should replace the parameters inside the prepared query
https://www.postgresql.org/message-id/9eacd36b-6ff3-d214-f36c-cce6b7df7f4b%40darold.net

<details>
<summary>
Note: The code added that replaces the parameters can actually be seen by running this command
</summary>

```
LESS="+/dump_all_queries &&" git diff 6ffd582ec67..98b38161ba99 pgbadger
```

---

</details>

And [again later at 2021-04-08](https://github.com/darold/pgbadger/issues/649#issuecomment-815566217) there's another confirmation
that pgbadger is able to handle bind parameters.

## Solution

I noticed that if I replaced **bind** with **execute** in Adam's @czterocyty tests

```
perl -p -i -e 's/bind <unnamed>/execute <unnamed>/g' t/fixtures/two.log t/fixtures/three.log
```

all his tests will pass.

<details>
<summary>Note on replacing bind with execute in the tests.</summary>

---

In [ticket 475](https://github.com/darold/pgbadger/issues/475#issuecomment-465855791) a user was parsing logs like these:

```
[DATE]:$CLIENT_IP($CLIENT_PORT):$USER@$DB:[$PID]:LOG:  duration: 117221.712 ms  execute <unnamed>: SELECT...
[DATE]:$CLIENT_IP($CLIENT_PORT):$USER@$DB:[$PID]:DETAIL:  parameters: $1 = 'NNNN'
```

That discussion was from 2019 and since the ticket was closed, that provided the needed hint.

---

</details>

So the remaining question is _"Where does **execute** feature as part of a regex in pgbadger and **bind** does not?"_
The following grep command gives the answer:

```bash
grep -n "\/.*execute.*\/" pgbadger | grep -v bind

16079:		if ($t_action !~ /query|statement|execute/)
16121:		return if ($t_action !~ /query|statement|execute/);
```

This is what PR #655 does, it adds bind to those two regexes, and then all the tests pass.

**Comment by wsdookadr** [comment]
UPDATE: My understanding [from Gilles' message](https://github.com/darold/pgbadger/pull/655#issuecomment-842657277) is the changes required are more involved, also there's a corner-case where both bind & execute show up for the same query being executed.

**Comment by darold** [comment]
Right, only execute statements are taken in account by pgbadger, parse and bind are not. If you don't have execute statement logged but only bind this is because bind is slower than the execute and their duration are bellow the value of log_min_duration_statement.
