### ISSUE TITLE
PGbadger insert query graph showing empty

### ISSUE THREAD

**Issue by ashx1901** [darold/pgbadger#679]
Hi,

I am getting an empty "insert/update/delete traffic" graph in pgbadger, Am i missing anything? Please help.

**Comment by darold** [comment]
Difficult to say but you may want to try with `-a 1` to have a 1 minute average instead of 5 minutes if you have too few writes per seconds  in the 5 minutes interval. In other terms if you have very few write you won't see them in the graphs. Looking at "Overview"/"General Activity" menu and the "Write Queries" tab you should see count > 0. If this is not the case and that there is write queries they are not registered to your PostgreSQL logs.

**Comment by ashx1901** [comment]
Hi, 

I tried using -a 1 but still getting the same result DML traffic still not showing up in the graph.

![pgbadger](https://user-images.githubusercontent.com/88678503/129071341-e26edab2-8839-4b4e-8acb-e990783b479a.JPG)

**Comment by ashx1901** [comment]
I missed mentioning in the above comment, We had run DML activity as a part of the load test, and the same we checked in datadog but I am not sure why it is not being reflected in pgbadger.

Thanks & Regards
Ashish

**Comment by darold** [comment]
How about "Overview"/"General Activity" menu and the "Write Queries" tab, what are the values reported? If all is 0 please post a part of your log with those DML and the pgbadger command.
