### ISSUE TITLE
Nested Function Calls

### ISSUE THREAD

**Issue by mowaiskhan** [darold/pgbadger#700]
Hi Team,
Thanks for a great tool.

I got a series of PL/SQL function calls nested within each other like

A->B->C->D->E

But, I can only see A being reported as time consuming. Why, we are not getting details for other nested functions as they are also problematic when it comes to take time.

Thanks,
Owais.

**Comment by gleu** [comment]
That's not due to pgBadger. pgBadger only analyzes your log files, and PostgreSQL only logs the top query (hence, your A function call).

You need to configure track_functions to pl in your postgresql.conf file, and you'll find what you need in the pg_stat_user_functions system view. But this is out of scope for pgBadger.

**Comment by mowaiskhan** [comment]
Thanks for prompt response.
