### ISSUE TITLE
monthly reports

### ISSUE THREAD

**Issue by fchapuis0101** [darold/pgbadger#718]
I try to generate monthly report

pgbadger -X --month-report 2919-08 /var/www/pg_reports/

What is this directory 2919-08, is it the directory that contains the pg logs?

When this command is executed,  I got following error:

pgbadger -X --month-report /var/log/postgresql/postgresql-10-2022-02* /var/www/pg_reports/

FATAL: logfile "/var/www/pg_reports/" must exist!
    - Error at line 2496

yet this directory exists.

Format of pg log: postgresql-10-2022-03-02.log

Thanks for your help

Fabrice

**Comment by darold** [comment]
```
    --month-report YYYY-MM : create a cumulative HTML report over the specified
                             month. Requires incremental output directories and
                             the presence of all necessary binary data files
```
That mean that this option must be used only in incremental mode (see -I option and documentation) which is not the case with your command `pgbadger -X --month-report /var/log/postgresql/postgresql-10-2022-02* /var/www/pg_reports/` and the error you are facing is because you have not set a value to the `--month-report ` option so it takes `/var/log/postgresql/postgresql-10-2022-02*` as the value.
