### ISSUE TITLE
Wrong time displayed on Graphs x-axis whereas times extracted from logs are correct

### ISSUE THREAD

**Issue by bbourgier** [darold/pgbadger#750]
Hi,

There is a 2 hours time discrepancy between:
- the right times parsed in my postgresql logs and displayed as texts in the pgBadger html report (here last time is 9AM which is good)
- the wrong time scale (x-axis) displayed in all the graphs (queries/sec, connections/sec): here the last time shown is 11AM which is NOT good. It should be 9AM

I attach screenshots for your comprehension.

Thanks in advance for your analysis and answers.

Bertrand
![pgBadger Graph Times Discrepancies](https://user-images.githubusercontent.com/1629011/189305941-2f40b7d8-47b0-42ad-a862-58854c505420.jpg)
![pgBadger Windows Server System Time](https://user-images.githubusercontent.com/1629011/189305943-08e8583a-fa36-4f2b-9242-0c6646dcedd8.jpg)
![postgreSQL Last Log File](https://user-images.githubusercontent.com/1629011/189305945-d9b1151d-77ab-4d5b-a1ed-c62646f8c542.jpg)

**Comment by darold** [comment]
Yes, the problem is that the timestamps shown in the Javascript graphs are based on your client host timezone and not the one of the log file. You can adjust the timezone for those graphs when building pgbadger reports using the `-Z or --timezone` option at command line. See `pgbadger --help` for usage.

**Comment by bbourgier** [comment]
Hi,

Ok I can do as you say and set --timezone parameter manually.
As my system timezone is "Europe/Paris", this is GMT+2 so I put:
**--timezone +2**
>> this means my system time is GMT+2

And this fixes the JS graphs. See the screenshot.
![pgBadger Graph Times OK with timezone param](https://user-images.githubusercontent.com/1629011/189382803-24e2c6f4-6497-4c9d-9185-2bc505e67006.jpg)

However I was wondering why this does not work WITHOUT this parameter.

As my postgresql log lines are tagged with a timezone:
2022-09-09 00:10:01.034 CEST [525932]: [2-1] user=...
And as CEST timezone is GMT+2 as well
This should be possible to select the x-axis time scale for the JS graphs without having to offset manually.
The drawback being that this offset may change depending on DST...

Well, thank you in any case for your answer.

Bertrand

**Comment by darold** [comment]
This is just because sometimes there is no timezone information and some other time the client is not at the same timezone and historically pgbadger doesn't take care of the timezone in the logs. Maybe this could be improved by using an advanced Date/Time Perl module but this is not in the pgbadger development policy.
